# Generated by Django 4.1.5 on 2023-03-04 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('novost', models.CharField(max_length=300, null=True, verbose_name='Новость')),
                ('date', models.DateField(null=True, verbose_name='Дата')),
                ('descp', models.TextField(null=True, verbose_name='Описание новости')),
                ('img', models.ImageField(null=True, upload_to='%Y/%m/%d')),
                ('author', models.CharField(max_length=100, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
